### ISSUE TITLE
Links to publicly available gene counts do not work

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#106]
Hi,
The links to publicly available gene counts (DOI links) do not work. They lead to a page that asks to request the data via "ILLiad" and that is not a feasible option.

**Comment by vyepez88** [comment]
Hi,
That's super weird, for me they work. I click on them and the Zenodo webpage opens directly. Then I click on the tar.gz file and I can download the dataset without any problem. Can you maybe try other browser?
Otherwise here are the links to each of them:
https://zenodo.org/record/3887451#.XzqrxvmxXJU
https://zenodo.org/record/3963474#.XzqsCPmxXJU
https://zenodo.org/record/3963470#.XzqsFfmxXJU

**Comment by gevro** [comment]
These links work. But the links on your main github drop page do not work on firefox. They work in Chrome.

**Comment by gevro** [comment]
Do you have a version of these gene counts for hg38?

**Comment by vyepez88** [comment]
I opened the links in firefox and they worked. For now, we only have them in hg19.
