### ISSUE TITLE
   L-BFGS-B needs finite values of 'fn' at runOutrider

### ISSUE THREAD

**Issue by marcDabad** [gagneurlab/drop#184]
Hi, 

I have this error and I don't know what to do:
```
Error in optim(pari, fn = truncLogLiklihoodD, gr = gradientD, k = ki,  :
      L-BFGS-B needs finite values of 'fn'
```

Running `rule AberrantExpression_pipeline_OUTRIDER_runOutrider_R`

It looks I haven't any error until this one.

**Comment by vyepez88** [comment]
Hi,
this usually happens when the sequencing depth of the samples varies too much. You can visualize this in the size factors plot in the counting summary. Maybe you spot a couple of samples that have either too low or too high size factors. OUTRIDER is then not able to fit these samples with too low counts and throws that error. Removing these samples should fix the error.

**Comment by marcDabad** [comment]
Hi, 

I'll check it an try again. 

Thanks for your help.

**Comment by marcDabad** [comment]
Thanks for your help, 
at the end it was a misslabeling of samples and strandness error. 
The strandnes was incorrect and obviously it didn't get the correct number of counts. 


Thanks.
