### ISSUE TITLE
WARNING: Less than 30 IDs in DROP_GROUP mae

### ISSUE THREAD

**Issue by csaygi** [gagneurlab/drop#201]
Hello everyone,

I would be very happy if I could learn more about the reason of a certain warning which appears when I run the mae pipeline: "WARNING: Less than 30 IDs in DROP_GROUP mae".

The minimum number of samples required for FRASER and OUTRIDER is specified in Yepez et al. However, I haven't seen such a suggestion for the mae analysis in neither Yepez et al nor Kremer et al.

Is the minimum of 30 samples really required for mae analysis to estimate the significance of the allele-specific expression?

I would be very glad if you could help. Thank you!

**Comment by nickhsmith** [comment]
Thanks for using DROP. I believe there may be a problem with your config file and/or sample_annotation table because MAE we don't actually set a suggested set of 30 IDs. My guess is that the group identifier in the config file used for MAE is actually being recognized by the AberrantExpression or AberrantSplicing modules.

If you could share your `config.yaml` and your `sample_annotation.tsv` table with us, we would probably be able to spot the issue. Otherwise I would make sure that you are specifying each sample with the module specific keyword. 

For example if you wanted to run MAE and AberrantExpression for sampleA you would need:

**config**
- mae:

   group: mae  

- aberrantExpression:

   group: outrider
  
**sample annotation table**
| RNA_ID  | DROP_GROUP  |
|  ----------- | ---------------------- | 
| sampleA | mae, outrider      |

**Comment by csaygi** [comment]
thank you for your reply! I am running drop pipeline for only mono-allelic expression analysis. 
snakemake mae --cores 10
Here is the config.yaml and sample_annotation.tsv files:

projectTitle: "DROP: Detection of RNA Outliers Pipeline"
root:             /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/
htmlOutputPath:   /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/
indexWithFolderName: true # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver 
sampleAnnotation: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/sample_annotation.tsv

geneAnnotation:
    # multiple annotations with custom names are possible
    # <annotation_name> : <path to gencode v29 annotation>
    v29:  /mnt/ref/Homo_sapiens/Ensembl/Homo_sapiens.GRCh38.103.gtf

genomeAssembly: GRCh38  # either hg19/hs37d5 or hg38/GRCh38
exportCounts:
    # specify which gene annotations to include and which 
    # groups to exclude when exporting counts
    geneAnnotations:
      - v29

mae:
    groups:
        - mae
    genome: Homo_sapiens.GRCh38.dna.primary_assembly.fa      # path to genome sequence in fasta format
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    maxVarFreqCohort: .05
    # VCF-BAM matching
    qcVcf: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/qc_vcf_1000G_GRCh38.vcf.gz 
    qcGroups: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

RNA_ID  RNA_BAM_FILE    DNA_VCF_FILE    DNA_ID  DROP_GROUP      PAIRED_END      COUNT_MODE      COUNT_OVERLAPS  STRAND  HPO_TERMS       GENE_COUNTS_FILE        ANNOTATION
S1493Nr10       S1493Nr10.RG_fixed.bam   S670Nr3_selected.vcf.gz  S670Nr3 mae     True    IntersectionStrict      True    No
S1493Nr45       S1493Nr45.RG_fixed.bam   S1008Nr7_selected.vcf.gz S1008Nr7        mae     True    IntersectionStrict      True  No
S1493Nr40       S1493Nr40.RG_fixed.bam   S670Nr6_selected.vcf.gz  S670Nr6 mae     True    IntersectionStrict      True    No
S1493Nr3        S1493Nr3.RG_fixed.bam    S670Nr36_selected.vcf.gz S670Nr36        mae     True    IntersectionStrict      True  No
S1493Nr5        S1493Nr5.RG_fixed.bam    S670Nr31_selected.vcf.gz S670Nr31        mae     True    IntersectionStrict      True  No
S1493Nr39       S1493Nr39.RG_fixed.bam   S670Nr25_selected.vcf.gz S670Nr25        mae     True    IntersectionStrict      True  No
S1493Nr16       S1493Nr16.RG_fixed.bam   S670Nr14_selected.vcf.gz S670Nr14        mae     True    IntersectionStrict      True  No
S1493Nr35       S1493Nr35.RG_fixed.bam   S670Nr11_selected.vcf.gz S670Nr11        mae     True    IntersectionStrict      True  No
S1493Nr43       S1493Nr43.RG_fixed.bam   S481Nr77_selected.vcf.gz S481Nr77        mae     True    IntersectionStrict      True  No
S1493Nr34       S1493Nr34.RG_fixed.bam   S1057Nr1_selected.vcf.gz S1057Nr1        mae     True    IntersectionStrict      True  No
S1493Nr46       S1493Nr46.RG_fixed.bam   S1008Nr8_selected.vcf.gz S1008Nr8        mae     True    IntersectionStrict      True  No
S1493Nr15       S1493Nr15.RG_fixed.bam   S427Nr4_selected.vcf.gz  S427Nr4 mae     True    IntersectionStrict      True    No
S1493Nr7        S1493Nr7.RG_fixed.bam    S670Nr17_selected.vcf.gz S670Nr17        mae     True    IntersectionStrict      True  No

**Comment by nickhsmith** [comment]
Thanks for sharing. I see the the likely issue.

When we originally built the pipeline we figured "everyone will want to run every module" which is not the case. The work around in this case should be the following.

1. You'll need to rebuild the `config.yaml` dictionary to contain the aberrantExpression and aberrantSplicing modules even though you don't want to run them. You can use the [template](https://github.com/gagneurlab/drop/blob/master/drop/template/config.yaml) or [demo config](https://github.com/gagneurlab/drop/blob/master/drop/demo/config_relative.yaml) yaml as a guide. The groups must be present for each module even if the group identifier is junk/isn't in the sample annotation table.
2. You'll need to use this branch `SA_errors` which can be done via git, or directly using `pip install git+https://github.com/gagneurlab/drop.git@SA_errors` which removes the minimum requirement per module to be run.
3. you'll want to rerun the mae pipeline as you had done before `snakemake mae --cores 10 -k`

Hopefully that makes sense, and we appreciate your patience. If that was unclear, or if any other problems arise please let us know and we will try to help again.

Know that we are currently refactoring our code to be truly modular, and so that this issue of errors due to unwanted modules finally goes away.

**Comment by nickhsmith** [comment]
please let us know if you continue to have problems. We are working on a new version push that will allow for each module to be turned on and off. Hopefully that will be done next week or the one after that.

**Comment by vyepez88** [comment]
Hi @csaygi, our latest version 1.1.0 allows you to specify which modules should be run. Please try it and let us know if you still encounter the errors.
