### ISSUE TITLE
Using the mae defined genome instead of the globally defined one

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#224]
Hi,
I am getting this error. What is this?
Thanks.

**Comment by nickhsmith** [comment]
This isn't actually an error, just a warning. We have added some new
features to DROP and as a result, want to define the genome variable in the
config globally instead of inside the MAE module. So it works perfectly
well for now, but if you want to utilize other features of drop 1.0.5
eventually you may want to alter the config.yaml file.

**Comment by gevro** [comment]
Ho do I configure the genome globally?

**Comment by nickhsmith** [comment]
You can follow the [template config file](https://github.com/gagneurlab/drop/blob/master/drop/template/config.yaml) and the [documentation](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html)

You define the genome variable using yaml formatting the same as you do in the MAE section, but outside of the MAE section.
