### ISSUE TITLE
SAMPLE1_snvParams.csv Param Files do not match. Updating to current Sample Annotation

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#225]
Hi,
I am getting this error: SAMPLE1_snvParams.csv Param Files do not match. Updating to current Sample Annotation

What does this mean?

**Comment by nickhsmith** [comment]
we track the sample annotation values so that if you change them it will retrigger any associated downstream runs, but again these are just warnings. This isn't an error and is in fact the desired behavior. This way you can see which parameters and samples are associated with your groups and analysis.
