### ISSUE TITLE
mae demo data

### ISSUE THREAD

**Issue by bijuissacch224610** [gagneurlab/drop#232]
Hi Drop Team

Is there a demo data specifically for MAE module that I could use to verify the workflow in my local implementation of DROP?

Thanks
-Biju

**Comment by nickhsmith** [comment]
you can follow the demo instructions, and specifically, call mae.

```
mkdir demo_dir
cd demo_dir
drop demo
snakemake mae --cores 1
```

This should work right away. The installation of some of the demo resources and running it may make some time. But hopefully it should all be done in ~20 minutes

**Comment by bijuissacch224610** [comment]
Hi Nick

the demo package has only 2 samples (from annotation file) assigned for MAE module. this is not enough to run MAE which requires at least 30 (as per DROP error). 

We ran the MAE pipeline scripts filterSNVs.sh and ASEReadCounter.sh on the 2 demo samples but failed to produce results in the ASEReadCounter step. To confirm, only column headers were generated without the alleleic counts. We verified the 'gatk ASEReadcounter' outside of DROP pipeline with similar results.
Do you have a verified demo dataset specifically for MAE module which you know generates successful results? I will be obliged if you could share the same. 

Thanks

**Comment by nickhsmith** [comment]
I'm sorry, I don't think I'm understanding your question then. We provide the demo dataset which indeed has 2 samples designated for the MAE module, but the minimum required sample for MAE in DROP is only 1 sample. For both aberrant expression and aberrant splicing we recommend more than 30 and require more than 10 samples, but these recommendations don't apply to MAE. In each of these 2 samples, the MAE pipeline successfully completes and identifies variants that are potentially expressed in an MAE fashion (although they aren't rare or significant in our example)

Are you running the GATK command on its own or as part of the pipeline? Unfortunately, I am unsure of exactly what the problem is. I understand that your data wasn't producing hits using ASEReadCounter, but it does for the 2 demo examples we provide as a showcase for DROP. As for a real world example, we get successful results in this [recent paper (preprint)](https://www.medrxiv.org/content/10.1101/2021.04.01.21254633v1.full.pdf) where MAE adds support with Aberrant Expression to diagnose 4 cases (page 18)

Please walk me through the problem, and if email is better you can email me directly at smith@in.tum.de

**Comment by nickhsmith** [comment]
worked through the problem offline. DROP demo works as expected
