### ISSUE TITLE
less than 30 IDs in DROP_GROUP when adding >300 external count IDs

### ISSUE THREAD

**Issue by noorsmal** [gagneurlab/drop#274]
I have 18 index samples that I want to compare to the external count files (139 and 269 fibroblast sample- count files provided on the github page) and I put them all in the sampleAnnotation file with DROP_GROUP = index.

However, when I run the pipeline, it gives a warning that there are less then 30 IDs in DROP_GROUP index and I don't see any change in the number of rules that are executed by the snakemake pipeline. I ran drop update and tried only running the aberrantExpression rule, but the warning stayed.

$drop --version
drop, version 1.1.0

$snakemake -n -c 8
WARNING: Less than 30 IDs in DROP_GROUP index

I added the config.yaml  and sampleAnnotation file (changed to .txt for upload)

[config.txt](https://github.com/gagneurlab/drop/files/7512135/config.txt)
[SampleAnnotation_batch1.txt](https://github.com/gagneurlab/drop/files/7512143/SampleAnnotation_batch1.txt)

**Comment by nickhsmith** [comment]
does it fail? Or are you concerned about the warning. I think the issue is that you are using the group name `index` for both aberrantExpression and aberrantSplicing, And in your config file you don't turn off the splicing module. So as a result, the aberrantSplicing module is throwing the warning (since unfortunately aberrantSplicing hasn't been fixed to allow external counts yet). Could you please try to run it again with aberrant splicing turned off?

You can do this by adding the line 
`run: false` to the aberrantSplicing module so that it looks like this

```
aberrantsplicing:
    run: false
    groups:
        - index 
    ... <and so on>
```

**Comment by noorsmal** [comment]
Thanks. I did not realize the aberrant splicing module was not fixed to allow external counts yet. I could not test if it works because of a different error, but I will open a new issue for this.
