### ISSUE TITLE
AttributeError: module 'drop' has no attribute 'getTmpDir'

### ISSUE THREAD

**Issue by bioinfous** [gagneurlab/drop#278]
Hello,
I am trying to run drop and keep getting this error.
AttributeError: module 'drop' has no attribute 'getTmpDir'
I re-installed drop to version 1.1.1 but still same error.
Please let me know how to fix this,
Thank you so much

**Comment by nickhsmith** [comment]
Sorry for the issue. Could you please let me know exactly how you are running drop and what the full error message is? This will help us track down the problem. Thanks

**Comment by bioinfous** [comment]
Hello,
I completely deleted DROP env and re-installed drop version 1.1.0 using conda, so far I am not getting an Attribute error.
Aberrant Expression is currently processing but Aberrant Splicing is giving this R error, here is the snippet:

processing file: /storage/le/home/ket/tmp/Rtmp9EHHh6/file152c85e4c2df4/00_define_datasets_from_anno.spin.Rmd
Load packages
Quitting from lines 26-29 (/storage/le/home/ket/tmp/Rtmp9EHHh6/file152c85e4c2df4/00_define_datasets_from_anno.spin.Rmd) 
Error: package or namespace load failed for 'devtools' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'memoise' 1.1.0 is being loaded, but >= 2.0.0 is required
Execution halted

R(4.0.5) is from drop env. 
Please let me know if there is an option for R to update the package,
Thank you

**Comment by nickhsmith** [comment]
It seems like you are having installation problems, with your underlying R installation. We recommend using 1.1.1 since this covers some bug fixes. The previous problem with getTmpDir is very odd. So I would recommend using 1.1.1 and hopefully we can work through that error.

Could you please let me know exactly how you are running drop? are you configuring which modules to run using the `run` variable in `config.yaml` or are you designating them at the `snakemake aberrantExpression` level? I appreciate your patience, and choosing DROP.

**Comment by nickhsmith** [comment]
Have there been any updates on your side?
