### ISSUE TITLE
How to rerun but with less samples

### ISSUE THREAD

**Issue by ChiaraF32** [gagneurlab/drop#380]
Hi, this is more of a question than an issue,

I have run DROP aberrant expression module on a group of 46 skeletal muscle RNAseq. 

I want to rerun the module, but I want to exclude 2 of the RNAseq samples from the analysis. 

I made a new sample annotation sheet that ommitted the two samples, and reran the execute command (see below)

```
snakemake aberrantExpression --touch --cores 12 &> MuscleOct2022-AE_1.log
```

But the `ods.Rds` file still included all of the samples, including the two that I ommitted from the sample annotation.

I know I could create a new project and rerun, but this would be more time consuming.

Any suggestions as for how to rerun without having to recompute things that don't need to be recomputed?

**Comment by vyepez88** [comment]
Hi, in theory DROP should recognize that 2 samples were removed. 
Maybe `touching` was not the best idea because as all outputs already exist, this command updated them and snakemake thinks nothing should be done.
What happens when you execute `snakemake -n aberrantExpression` ?

The first file that should be modified with the removal of samples is the merged total counts.
What happens when you execute: `snakemake -n {root_dir}/processed_data/aberrant_expression/{gene_annotation}/outrider/{drop_group}/total_counts.Rds` ?
If it indeed shows the desired step, you can change `-n` with `-f` which will execute that step only. And then run the rest of the pipeline with:
`snakemake aberrantExpression`

**Comment by ChiaraF32** [comment]
When I execute `snakemake -n aberrantExpression` and `snakemake -n {root_dir}/processed_data/aberrant_expression/{gene_annotation}/outrider/{drop_group}/total_counts.Rds` DROP does not recognise that changes have been made:

```
WARNING: 1 files missing in samples annotation. Ignoring...
check for missing R packages
MonoallelicExpression has been turned off in the config file
rnaVariantCalling has been turned off in the config file
Structuring dependencies...
Dependencies file generated at: /tmp/tmpzchiiqf6

Building DAG of jobs...
Nothing to be done (all requested files are present and up to date).
```

**Comment by vyepez88** [comment]
What about
`snakemake -nf {root_dir}/processed_data/aberrant_expression/{gene_annotation}/outrider/{drop_group}/total_counts.Rds`

**Comment by ChiaraF32** [comment]
That worked, thanks for you help.
