### ISSUE TITLE
BAM file alignment

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#42]
Hi,
Does the alignment software need to be the same for all samples? For example, I would like to use GTEx samples that are only available as BAM files. However, the read aligner that GTEx used is different than the one I use. Is it ok to use my BAM files together with GTEx BAM files?

Also, GTEx aligned to GENCODE v26, while I aligned to GENCODE v32. So the transcriptome references used were different.

Same question for VCF input files.
Thanks.

**Comment by mumichae** [comment]
In order to minimise batch effects, the alignment tool should be the same and GTEX samples should be chosen from the same tissue as the remaining dataset.
The gene reference should definitely be the same, as we use if for quantifying genes based on it. We are working on a feature that allows giving count matrices as input, which would make things easier, however for now making sure the annotation files are the same as the one given in the config file is crucial.
Adding additional samples is only necessary if your dataset has less than 50-60 samples in total. If you do add the GTEX samples, make sure to include a sufficient number of them (e.g. number of samples in your current dataset). Too few single GTEX BAM files will otherwise lead to an inflation of false positives.
