### ISSUE TITLE
Split read recount should actually do a recount

### ISSUE THREAD

**Issue by aerval** [gagneurlab/drop#472]
Hej,

I was running the DROP abberant splicing detection but had a problem with my bam index files that lead to 0 detected read counts and with that do errors done the pipeline (but not in steps 2 and 3 of the split read detection, there the pipeline simply finds 0 reads and thus 0 splice junctions). Now I fixed the bam index and was re-executing the pipeline, counting finds the reads but they are still lost after merge. Now I found that the merge does specifically prevent recounting, i.e:

https://github.com/gagneurlab/drop/blob/594d7daaff872604d65ae1537a0fe59f463de6b3/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L49-L50

In my books, that is a bug. If counts are merged again, they should be recounted, right? I know it is an expensive step but in my case, that seems to create an issue. At least this should be a parameter and I should not have to dive into the code when I have an issue with a bam index?

Cheers, Philipp

**Comment by ischeller** [comment]
Hi @aerval , there is the parameter `recount` in the config that forces samples to be recounted if set to true. Did you set this parameter to True? Otherwise DROP might not recognize that it needs to do the merging anew and starts from temp files. This is what this line takes care of
https://github.com/gagneurlab/drop/blob/594d7daaff872604d65ae1537a0fe59f463de6b3/drop/modules/aberrant-splicing-pipeline/Counting/01_2_countRNA_splitReads_merge.R#L44-L46 
Related to the line of code that you point to: At this point, the recounting per sample is already done when the script `01_2_countRNA_splitReads_merge.R` is called. So we don't want to recount yet another time, but rather just need to collect the results of the counting per sample. This is why `recount=FALSE` in this function, which is indeed intended. 

Let us know in case you did set `recount: True` but still did not get the counts after merging.

**Comment by aerval** [comment]
I see, that makes perfect sense. However, I hadn't considered that as the `01_1_countRNA_splitReads_samplewise.R` jobs did change from ` no. splice junctions (split counts) = 0` to i.e ` no. splice junctions (split counts) = 398234` but the merge job doesn't? (*Hm, maybe because I somehow at some point deleted the per sample counts???*)

**Comment by ischeller** [comment]
If you manually deleted the sample-wise counts but didn't set `recount: true`, this could indeed explain the behavior you observed.  In this case, the next time you ran DROP after deleting those files, they would get recounted as they don't exist, but the temp file from the previous merging step will still exist and would be used for creating the merged counts unless `recount: true` in the config.

**Comment by aerval** [comment]
Then it makes sense, great! Danke schön!
