### ISSUE TITLE
Using external count in FRASER2?

### ISSUE THREAD

**Issue by thudaniel2333** [gagneurlab/drop#487]
Hi,
I'm wondering if external count is supported in FRASER2. If yes, what are the required input files and shall we use the same sample annotation file as in FRASER1?
I'd also like to convert my local bam files to splice count files so that we don't need to recount for every batch of samples. I noticed that the splice counts can be found in both 'processed_data/aberrant_splicing/datasets/cache' and 'processed_data/aberrant_splicing/datasets/savedObjects/' directories. Can these files be directly used as the external counts? If not, can we convert these files into the required external counts?

Thanks in advance!
Daniel

**Comment by ischeller** [comment]
Hi @thudaniel2333 , 
yes, external counts are supported when using FRASER2. You'll need the same files as for FRASER1, listed [here](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#using-external-counts).

Regarding your second question: 
-  You don't need to recount completely for all samples when only a few new samples are added. By default (with `recount: false` in the config.yaml), you will see that DROP runs the split_count counting steps for all samples,  however it will simply read in the stored cache file for samples that have previously been counted (so this should be very fast). For the non-split counts, however, the set of splice sites for which those should be counted depends on the combined introns across all samples in the specific DROP_GROUP, so these will change when more samples are added and therefore will have to be counted again.
- You can convert existing counts into the files needed to use as external counts with the `exportCounts` rule (as described in the documentation linked above). Note however, that because rare introns may be personally identifiable the `exportCounts` command only exports regions canonically mentioned in the gtf file. So this might not be optimal for you when all your data is local and you want to keep rare introns. 
-  You can also use the fds-object saved at processed_data/aberrant_splicing/datasets/savedObjects/raw-local-{DROP_GROUP}/ to manually create external counts without this filtering step. For this, it is probably easiest if you simply modify the script used by DROP to create the external counts, in particularly I think you have to remove [this line](https://github.com/gagneurlab/drop/blob/594d7daaff872604d65ae1537a0fe59f463de6b3/drop/modules/aberrant-splicing-pipeline/Counting/exportCounts.R#L45C41-L45C48) . 

I hope this is helpful to answer your questions. Let us know if you have more questions regarding this.

**Comment by thudaniel2333** [comment]
Thank you for the prompt reply! 

If we use the fds-object to manually create external counts, will the rare introns not in the gtf file be included in the external counts?

**Comment by ischeller** [comment]
Yes, that is possible, I believe that removing [this line](https://github.com/gagneurlab/drop/blob/594d7daaff872604d65ae1537a0fe59f463de6b3/drop/modules/aberrant-splicing-pipeline/Counting/exportCounts.R#L45) from the script that we wrote to export the external counts should be enough to achieve that. 
But note that when merging with external counts, only introns / splice sites present in both the local fds and the external counts will be present after the merging, so you still might miss rare introns that are only present in the new samples that you are adding.

**Comment by thudaniel2333** [comment]
Will it work if we merge two external counts made from local files by assigning 0 to the non-overlapping introns/sites?  If that works we'd be able to merge the external counts made from two batches of local data without removing the non-overlapping sites. In this way we'll just need to store the external count files and get rid of the cached intermediate files or bam files and the final output will be the same, which would make it a lot easier to combine different batches of data when running the aberrant splice module.

**Comment by ischeller** [comment]
I would not recommend to assign 0 to non-overlapping sites when merging external counts, at the very least you should be very careful when doing such a thing (it should work though). The problem with this is that later you don't know if a certain sample was a true 0 (i.e. there were indeed no reads for this intron/splice site) or whether it there might have been reads but e.g. the site was simply not counted in this sample. This can happen especially for the non-split counts, as by default in DROP we count them only at splice sites of introns that pass the `minExpressionInOneSample` filter, to save time. So basically zeros in the non-overlapping sites can have 2 different meanings, which is problematic.
