### ISSUE TITLE
Problem running DROP

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#539]
Hello, first of all, thank you for all your work. I was trying to use DROP to perform an analysis with FRASER 2.0 as I have been having issues with it using it in R. I have downloaded and installed it via mamba as well as snakemake < v8 (as with newer versions are incompatible due to a problem with wbuild). I have downloaded the drop demo and tried a dry run 2-3 times, but I get the same error (its a long one so I will attach 2 screenshots of the first part of it):

![drop_error_1](https://github.com/gagneurlab/drop/assets/119602950/4f65954f-f5cc-413c-8dd3-72dbc24a7a31)
![drop_error_2](https://github.com/gagneurlab/drop/assets/119602950/e6c71d8a-18ec-4e46-bca6-f633e11d6e4f)

I can see it says there are files missing, but I'm using the data from the drop demo, so I can't figure out the issue here. In case this is relevant, I'm using ubuntu on windows (no powershell). If I could have some help elucidating what is going wrong and why the dry run is giving me problems already. Thank you in advance!

Miriam Martínez

**Comment by AtaJadidAhari** [comment]
Hi,

from the screenshots that you've sent it looks like the dry run was finished successfully. This is the expected behavior of snakemake, and the "missing files" are the outputs that will be created from each rule. For example `rule create_dict` will be run because its outputs, `chr21.dict` and `chr21_ncbi.dict` are missing. All inputs to this rule i.e. `chr21_ncbi.fa` and `chr21.fa`,  should be already there under `Data` folder if you ran `drop demo`.
Please note that you might face further issues when running the pipeline because of the new FRASER version, which will be fixed in the next couple of days once a new version of DROP is released. 

Best,

Ata

**Comment by mmartinezj** [comment]
Hi Ata,

thanks for the quick response! I'm not very familiar with snakemake and thought all this missing files were errors popping due to a problem with my DROP installation. Also, thanks for the warning regarding further issues with the new FRASER version. I will wait until the next version if I come up with any issues in case the new DROP version solves it. 

Best,

Miriam
