### ISSUE TITLE
Error in Aberrant Expression Analysis with only external counts

### ISSUE THREAD

**Issue by bijuissac** [gagneurlab/drop#561]
Hi Team

I am trying to run AE pipeline with only external counts but it gives error

Quitting from lines 62-67 [unnamed-chunk-5] (/hpcdata/scratch/25550129.1.all.q/RtmpUSQCPG/file3e615edaefc8/SampleAnnotation.spin.Rmd)
Error in `file.exists()`:
! invalid 'file' argument
Backtrace:
 1. sa[, `:=`(aux1, file.exists(RNA_BAM_FILE))]
 2. data.table:::`[.data.table`(sa, , `:=`(aux1, file.exists(RNA_BAM_FILE)))
 3. base::eval(jsub, SDenv, parent.frame())
 4. base::eval(jsub, SDenv, parent.frame())
 5. base::file.exists(RNA_BAM_FILE)
Execution halted

However, if I provide even a single BAM, it seems to proceed to next step. 

Does the pipeline work if we only have external counts? Does the pipeline need a BAM?

**Comment by AtaJadidAhari** [comment]
Hi @bijuissac, 

Thanks for using DROP! 
I checked and there is indeed a problem on how we check the non-existent `RNA_BAM_FILE`s. Currently if all of the samples are external, your error will occur. Thanks for noticing this, we will fix it in the next DROP release!

As a workaround, as you mentioned you can add one dummy sample and fill the `RNA_BAM_FILE` entry in sample_annotation file, a dummy path like `test.bam` will work since the BAM file doesn't need to exist. Also give that sample a different `DROP_GROUP` name and run the pipeline again.

**Comment by vyepez88** [comment]
Hi, to add to this, we initially designed DROP not to accept external counts only, as if you already have the count matrix of your cohort, you can simply run OUTRIDER on it in 4 lines:

1. convert the count matrix to an ods object
2. filter it
3. run OUTRIDER
4. extract the results

which is way easier than setting up DROP.

**Comment by AtaJadidAhari** [comment]
Hi @bijuissac, any updates on this issue? did you try running OUTRIDER separately and without DROP as Vicente suggested? If it still persists, you can try installing DROP from the dev branch, where I have implemented a fix for your issue that will also be available in the next DROP release.

**Comment by bijuissac** [comment]
Hi

I did run OUTRIDER separately and it worked.

Thanks
