### ISSUE TITLE
Result doubts 2

### ISSUE THREAD

**Issue by mmartinezj** [gagneurlab/drop#570]
Hello,

Some time ago, I asked for help with interpreting FRASER2.0 output. I apologize for bringing up the issue again, but as I reviewed the results, I encountered another question that I was hoping you could help me with. I need to better understand how FRASER processes the information so that I can draw accurate conclusions from the output. 

After running FRASER2.0, the results indicated that 4 genes are likely to experience a frameshift (image attached), being the potential impact exonTruncation&Elongation or exonElongation. If I understand correctly, the width column on the results table corresponds to the width of the intron where FRASER has detected the event (not the width of the event per se). If so, how does FRASER determine that a frameshift has occurred if the width of the event isn't explicitly specified in the output? Is there a way I can extract the length of the event so that I can verify it myself?

![frameshift_genes](https://github.com/user-attachments/assets/c4afc42b-58e8-49eb-a816-f420158ed9e0)

Other potentialImpact I would like to understand better would be the annotatedIntron_reducedUsage. Does this refer to an expected usage of an annotated intron for each gene, and if there are fewer reads than expected in that intron, it is classified as this type of event??

Additionally, I have a question regarding the "blacklist" column—what does it refer to, and what are the implications of an entry being blacklisted?

I haven't found detailed information on these points in the documentation/papers/vignettes related to FRASER2.0. While I’ve come across information about FRASER, the specifics for FRASER2.0 seem to be less accessible. It’s possible that this information is available, but I haven’t been able to locate it. If this is covered somewhere in the documentation, papers, or vignettes, I apologize for bringing it up again, and I would be very grateful if you could direct me to where this information can be found. If not, I would appreciate any assistance you could provide to help me fully understand the output.

Thank you very much in advance!

Best,

Miriam

**Comment by ischeller** [comment]
Hi @mmartinezj , 

1) Yes, the width column contains the width of the intron that was detected as aberrant. To determine if an event is a likely frameshift, we compare the start and end positions of the intron to the coordinates of the annotated exons in the provided gene annotation file. To verify this label for yourself (which we recommend doing), you could use a genome browser such as IGV and visually check the reads and introns of your outlier sample relative to the annotated exons. Or you can load the txdb object that DROP creates from your provided gene annotation and check the coordinates of annotated exons there directly, e.g.
```
library(AnnotationDbi)
txdb <- loadDb(txdb_file) # txdb_file found at {DROP_processed_data_dir}/preprocess/{annotation}/txdb.db
exons(txdb)
```

2) annotatedIntron_reducedUsage refers to the intron detected as an outlier being i) present in the provided annotation and ii) being used at a lower ratio in the outlier sample compared to the other samples in your dataset.

3) The blacklist column refers to certain regions of the genome where it is difficult to align reads properly during the alignment step, e.g. due to the region being very repetitive. These regions are referred to as 'blacklist regions' and they tend to be more noisy. As a result, outlier calls from introns that are in part or completely overlapping with such a blacklist region are flagged, and we consider them in general less reliable than calls from outside blacklist regions. 

As you pointed out, some of these outputs are indeed not covered well in our vignettes and examples currently, thank you for bringing that to our attention. I hope these answers help to solve your questions. Good luck with your analysis!

Best,
Ines

**Comment by mmartinezj** [comment]
Hello,
thank you very much for your time answering these questions and all the help provided. It really helps for understanding the output and how the tool works. Amazing job setting up and maintaining this tool, keep it up!

Best,

Miriam
