### ISSUE TITLE
n+1 runs

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#95]
If I have a new RNA-seq sample, is there any way to add it to an existing analysis set so that the pipeline only has to redo the jobs that require that new sample, without having to rerun the entire pipeline from the beginning for all the samples?

**Comment by vyepez88** [comment]
The pipeline was designed thinking about this possibility. Simply add the sample to the sample annotation file as a new row. 
For the aberrant expression module, it will count only that sample, then merge, filter and run OUTRIDER in all of them. In this way you avoid counting N-1 samples.
For the aberrant splicing module, it will count the split reads of only that sample, then merge, create the junction for the non-split reads (because this sample could have added new splice sites not seen before), count the split-reads, merge, filter and run FRASER in all samples. You avoid counting the split reads of N-1 samples. Be sure to have the parameter recount=FALSE, so that it doesn't perform the split reads of the N-1 samples.
For the mae module, it will perform the allelic counts and test on this sample only. Afterwards it will merge the results.

**Comment by gevro** [comment]
Ok great.
